module.exports = class Data1772671069609 {
    name = 'Data1772671069609'

    async up(db) {
        await db.query(`CREATE TABLE "transaction" ("id" character varying NOT NULL, "hash" text NOT NULL, "block_number" integer NOT NULL, "timestamp" integer NOT NULL, CONSTRAINT "PK_89eadb93a89810556e1cbcd6ab9" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_de4f0899c41c688529784bc443" ON "transaction" ("hash") `)
        await db.query(`CREATE TABLE "trade_action" ("id" character varying NOT NULL, "account" text NOT NULL, "event_name" text NOT NULL, "market_address" text, "order_type" integer NOT NULL, "order_key" text NOT NULL, "is_long" boolean, "swap_path" text array NOT NULL, "initial_collateral_token_address" text NOT NULL, "initial_collateral_delta_amount" numeric NOT NULL, "size_delta_usd" numeric, "size_delta_in_tokens" numeric, "acceptable_price" numeric, "execution_price" numeric, "trigger_price" numeric, "contract_trigger_price" numeric, "index_token_price_min" numeric, "index_token_price_max" numeric, "collateral_token_price_min" numeric, "collateral_token_price_max" numeric, "min_output_amount" numeric, "execution_amount_out" numeric, "position_fee_amount" numeric, "borrowing_fee_amount" numeric, "funding_fee_amount" numeric, "liquidation_fee_amount" numeric, "collateral_total_cost_amount" numeric, "pnl_usd" numeric, "base_pnl_usd" numeric, "price_impact_usd" numeric, "price_impact_diff_usd" numeric, "price_impact_amount" numeric, "swap_impact_usd" numeric, "twap_group_id" text, "number_of_parts" integer, "total_impact_usd" numeric, "proportional_pending_impact_usd" numeric, "reason" text, "reason_bytes" text, "should_unwrap_native_token" boolean, "decrease_position_swap_type" integer, "ui_fee_receiver" text NOT NULL, "src_chain_id" numeric, "timestamp" integer NOT NULL, "transaction_id" character varying, CONSTRAINT "PK_9bf0f9939de145fbea4117cbb48" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_fbe5bb206a653d096b723f9a83" ON "trade_action" ("account") `)
        await db.query(`CREATE INDEX "IDX_39d9f66737b783b42b58886d45" ON "trade_action" ("event_name") `)
        await db.query(`CREATE INDEX "IDX_aeddd1ffbafd3791ac95aade2e" ON "trade_action" ("market_address") `)
        await db.query(`CREATE INDEX "IDX_8751bc3ea47c0c373f0942014a" ON "trade_action" ("order_key") `)
        await db.query(`CREATE INDEX "IDX_6a08a35b1cd69e340c608fdfd4" ON "trade_action" ("transaction_id") `)
        await db.query(`CREATE INDEX "IDX_5413319a6a49c7e4aa3f191b54" ON "trade_action" ("timestamp") `)
        await db.query(`CREATE TABLE "position" ("id" character varying NOT NULL, "account" text NOT NULL, "market" text NOT NULL, "collateral_token" text NOT NULL, "is_long" boolean NOT NULL, "account_stat_id" character varying, "size_in_usd" numeric NOT NULL, "size_in_tokens" numeric NOT NULL, "collateral_amount" numeric NOT NULL, "entry_price" numeric NOT NULL, "max_size" numeric NOT NULL, "realized_fees" numeric NOT NULL, "unrealized_fees" numeric NOT NULL, "realized_price_impact" numeric NOT NULL, "unrealized_price_impact" numeric NOT NULL, "realized_pnl" numeric NOT NULL, "unrealized_pnl" numeric NOT NULL, "snapshot_timestamp" integer, "is_snapshot" boolean NOT NULL, "created_at" integer NOT NULL, "updated_at" integer NOT NULL, CONSTRAINT "PK_b7f483581562b4dc62ae1a5b7e2" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_a3fa7add1f44aea63006e09e46" ON "position" ("account") `)
        await db.query(`CREATE INDEX "IDX_c5575b15c2af612abeedeb69a1" ON "position" ("market") `)
        await db.query(`CREATE INDEX "IDX_position_account_stat" ON "position" ("account_stat_id") `)
        await db.query(`CREATE TABLE "account_stat" ("id" character varying NOT NULL, "closed_count" integer NOT NULL, "wins" integer NOT NULL, "losses" integer NOT NULL, "volume" numeric NOT NULL, "cumsum_size" numeric NOT NULL, "cumsum_collateral" numeric NOT NULL, "sum_max_size" numeric NOT NULL, "max_capital" numeric NOT NULL, "net_capital" numeric NOT NULL, "deposits" numeric NOT NULL, "realized_pnl" numeric NOT NULL, "realized_fees" numeric NOT NULL, "realized_price_impact" numeric NOT NULL, "realized_swap_impact" numeric NOT NULL, "updated_at" integer NOT NULL, CONSTRAINT "PK_ced22b9c2e7bb5e1cf727e92439" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "period_account_stat" ("id" character varying NOT NULL, "account" text NOT NULL, "period_start" integer NOT NULL, "period_end" integer NOT NULL, "closed_count" integer NOT NULL, "wins" integer NOT NULL, "losses" integer NOT NULL, "volume" numeric NOT NULL, "cumsum_size" numeric NOT NULL, "cumsum_collateral" numeric NOT NULL, "sum_max_size" numeric NOT NULL, "max_capital" numeric NOT NULL, "net_capital" numeric NOT NULL, "realized_pnl" numeric NOT NULL, "realized_fees" numeric NOT NULL, "realized_price_impact" numeric NOT NULL, "start_unrealized_pnl" numeric NOT NULL, "start_unrealized_fees" numeric NOT NULL, "start_unrealized_price_impact" numeric NOT NULL, "has_rank" boolean NOT NULL, CONSTRAINT "PK_bb314171072baedd47be0852416" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_d48ad46979ace63b6a99c82d2b" ON "period_account_stat" ("account") `)
        await db.query(`CREATE INDEX "IDX_49fb299d0694f14b715a9ea3d5" ON "period_account_stat" ("period_start") `)
        await db.query(`CREATE TABLE "claim_action" ("id" character varying NOT NULL, "account" text NOT NULL, "event_name" text NOT NULL, "market_addresses" text array NOT NULL, "token_addresses" text array NOT NULL, "amounts" text array NOT NULL, "token_prices" text array NOT NULL, "is_long_orders" boolean array NOT NULL, "timestamp" integer NOT NULL, "transaction_id" character varying, CONSTRAINT "PK_43091688806d31df16f7466909e" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_33744b9169fe21b2074c854119" ON "claim_action" ("account") `)
        await db.query(`CREATE INDEX "IDX_30de987ce5da34390955969a16" ON "claim_action" ("timestamp") `)
        await db.query(`CREATE INDEX "IDX_4b733c1ff5148f63e68bdb7f8d" ON "claim_action" ("transaction_id") `)
        await db.query(`CREATE TABLE "claimable_collateral" ("id" character varying NOT NULL, "account" text NOT NULL, "market_address" text NOT NULL, "token_address" text NOT NULL, "time_key" text NOT NULL, "value" numeric NOT NULL, "factor" numeric NOT NULL, "reduction_factor" numeric NOT NULL, "factor_by_time" numeric NOT NULL, "claimed" boolean NOT NULL, "updated_at" integer NOT NULL, CONSTRAINT "PK_2925845d74f85521bfbba01526d" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_96cd78c49099592bff934e39a6" ON "claimable_collateral" ("account") `)
        await db.query(`CREATE TABLE "deposit_action" ("id" character varying NOT NULL, "account" text NOT NULL, "event_name" text NOT NULL, "market_address" text NOT NULL, "initial_long_token" numeric, "initial_short_token" numeric, "received_market_tokens" numeric, "execution_fee" numeric, "callback_gas_limit" numeric, "key" text NOT NULL, "timestamp" integer NOT NULL, "transaction_id" character varying, CONSTRAINT "PK_86105b9fba0e873c9f0cff80dba" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_e4aba1be4c95e97b75423e303e" ON "deposit_action" ("account") `)
        await db.query(`CREATE INDEX "IDX_10ab0e4970802f405284cf09fd" ON "deposit_action" ("event_name") `)
        await db.query(`CREATE INDEX "IDX_485a8a6db05713181d7fb053f7" ON "deposit_action" ("market_address") `)
        await db.query(`CREATE INDEX "IDX_745beaf1a91bd7269f32625772" ON "deposit_action" ("key") `)
        await db.query(`CREATE INDEX "IDX_2c835fdeb834a15d27442b0f62" ON "deposit_action" ("timestamp") `)
        await db.query(`CREATE INDEX "IDX_8de64f2caf1adb5ab2b574dead" ON "deposit_action" ("transaction_id") `)
        await db.query(`CREATE TABLE "withdrawal_action" ("id" character varying NOT NULL, "account" text NOT NULL, "event_name" text NOT NULL, "market_address" text NOT NULL, "market_token_amount" numeric, "received_long_token_amount" numeric, "received_short_token_amount" numeric, "execution_fee" numeric, "callback_gas_limit" numeric, "key" text NOT NULL, "timestamp" integer NOT NULL, "transaction_id" character varying, CONSTRAINT "PK_51b7c88659c783368e03eedfced" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_9ee6a688101a9f1433ebb48416" ON "withdrawal_action" ("account") `)
        await db.query(`CREATE INDEX "IDX_751ebec57c8dca0dd792498d2f" ON "withdrawal_action" ("event_name") `)
        await db.query(`CREATE INDEX "IDX_226e54d555acc2ff8e497a86d9" ON "withdrawal_action" ("market_address") `)
        await db.query(`CREATE INDEX "IDX_487ae444a372dab62dd88c7fba" ON "withdrawal_action" ("key") `)
        await db.query(`CREATE INDEX "IDX_fbaed929abd3390b2f676da218" ON "withdrawal_action" ("timestamp") `)
        await db.query(`CREATE INDEX "IDX_4aea3902e1d161ae8eab306b98" ON "withdrawal_action" ("transaction_id") `)
        await db.query(`CREATE TABLE "market_info" ("id" character varying NOT NULL, "market_token_address" text NOT NULL, "index_token_address" text NOT NULL, "long_token_address" text NOT NULL, "short_token_address" text NOT NULL, "is_disabled" boolean NOT NULL, "long_pool_amount" numeric NOT NULL, "short_pool_amount" numeric NOT NULL, "max_long_pool_amount" numeric NOT NULL, "max_short_pool_amount" numeric NOT NULL, "max_long_pool_usd_for_deposit" numeric NOT NULL, "max_short_pool_usd_for_deposit" numeric NOT NULL, "pool_value_max" numeric NOT NULL, "pool_value_min" numeric NOT NULL, "reserve_factor_long" numeric NOT NULL, "reserve_factor_short" numeric NOT NULL, "open_interest_reserve_factor_long" numeric NOT NULL, "open_interest_reserve_factor_short" numeric NOT NULL, "long_open_interest_usd" numeric NOT NULL, "short_open_interest_usd" numeric NOT NULL, "long_open_interest_in_tokens" numeric NOT NULL, "short_open_interest_in_tokens" numeric NOT NULL, "max_open_interest_long" numeric NOT NULL, "max_open_interest_short" numeric NOT NULL, "min_collateral_factor" numeric NOT NULL, "min_collateral_factor_for_open_interest_long" numeric NOT NULL, "min_collateral_factor_for_open_interest_short" numeric NOT NULL, "funding_factor" numeric NOT NULL, "funding_exponent_factor" numeric NOT NULL, "funding_increase_factor_per_second" numeric NOT NULL, "funding_decrease_factor_per_second" numeric NOT NULL, "threshold_for_stable_funding" numeric NOT NULL, "threshold_for_decrease_funding" numeric NOT NULL, "min_funding_factor_per_second" numeric NOT NULL, "max_funding_factor_per_second" numeric NOT NULL, "total_borrowing_fees" numeric NOT NULL, "borrowing_factor_per_second_for_longs" numeric NOT NULL, "borrowing_factor_per_second_for_shorts" numeric NOT NULL, "position_impact_pool_amount" numeric NOT NULL, "min_position_impact_pool_amount" numeric NOT NULL, "position_impact_pool_distribution_rate" numeric NOT NULL, "swap_impact_pool_amount_long" numeric NOT NULL, "swap_impact_pool_amount_short" numeric NOT NULL, "lent_position_impact_pool_amount" numeric, "position_impact_factor_positive" numeric, "position_impact_factor_negative" numeric, "max_position_impact_factor_positive" numeric, "max_position_impact_factor_negative" numeric, "max_position_impact_factor_for_liquidations" numeric, "position_impact_exponent_factor" numeric, "swap_impact_factor_positive" numeric, "swap_impact_factor_negative" numeric, "swap_impact_exponent_factor" numeric, "max_lendable_impact_factor" numeric, "max_lendable_impact_factor_for_withdrawals" numeric, "max_lendable_impact_usd" numeric, "position_fee_factor_for_positive_impact" numeric NOT NULL, "position_fee_factor_for_negative_impact" numeric NOT NULL, "swap_fee_factor_for_positive_impact" numeric NOT NULL, "swap_fee_factor_for_negative_impact" numeric NOT NULL, "atomic_swap_fee_factor" numeric NOT NULL, "max_pnl_factor_for_traders_long" numeric NOT NULL, "max_pnl_factor_for_traders_short" numeric NOT NULL, "funding_factor_per_second" numeric, "longs_pay_shorts" boolean, "virtual_pool_amount_for_long_token" numeric, "virtual_pool_amount_for_short_token" numeric, "virtual_inventory_for_positions" numeric, "virtual_market_id" text, "virtual_long_token_id" text, "virtual_short_token_id" text, "created_at" integer NOT NULL, "updated_at" integer NOT NULL, CONSTRAINT "PK_b5c73bcd5128c538b622a6a665b" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_8f2087423919ebcabfd54d30cf" ON "market_info" ("market_token_address") `)
        await db.query(`CREATE TABLE "volume_info" ("id" character varying NOT NULL, "market" text NOT NULL, "period" text NOT NULL, "volume_usd" numeric NOT NULL, "timestamp" integer NOT NULL, CONSTRAINT "PK_81f03620089c8b453fbf945f683" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_26a9a2fc81da7ab69d032a6141" ON "volume_info" ("market") `)
        await db.query(`CREATE INDEX "IDX_24b9e4d52476c0d729a784988a" ON "volume_info" ("timestamp") `)
        await db.query(`CREATE TABLE "positions_volume" ("id" character varying NOT NULL, "market" text NOT NULL, "volume" numeric NOT NULL, "timestamp" integer NOT NULL, CONSTRAINT "PK_984647a055cd817bcb656caa31e" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_20a3b78659fbd92e1d4e01ec8a" ON "positions_volume" ("market") `)
        await db.query(`CREATE INDEX "IDX_9f8f59bbb384b9760c0388c4ef" ON "positions_volume" ("timestamp") `)
        await db.query(`CREATE TABLE "apr_snapshot" ("id" character varying NOT NULL, "address" text NOT NULL, "apr_by_fee" numeric NOT NULL, "apr_by_borrowing_fee" numeric NOT NULL, "snapshot_timestamp" integer NOT NULL, CONSTRAINT "PK_9853ceac1688a075f78069e8dfb" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_52711af5befe03f9f9f07ef179" ON "apr_snapshot" ("address") `)
        await db.query(`CREATE INDEX "IDX_5174013c1a7dd4a570c72d2507" ON "apr_snapshot" ("snapshot_timestamp") `)
        await db.query(`CREATE TABLE "fees_info" ("id" character varying NOT NULL, "period" text NOT NULL, "total_borrowing_fee_usd" numeric NOT NULL, "total_position_fee_usd" numeric NOT NULL, "total_liquidation_fee_usd" numeric NOT NULL, "total_swap_fee_usd" numeric NOT NULL, "timestamp" integer NOT NULL, CONSTRAINT "PK_4356efed40205b53aa157d1fe58" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_755a9275c12efab4c4a54adef4" ON "fees_info" ("period") `)
        await db.query(`CREATE INDEX "IDX_25cadba7648fd93f8232747654" ON "fees_info" ("timestamp") `)
        await db.query(`CREATE TABLE "user_stat" ("id" character varying NOT NULL, "unique_users" integer NOT NULL, "timestamp" integer NOT NULL, CONSTRAINT "PK_d50934a678f287072b9f949123f" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "glv_deposit_action" ("id" character varying NOT NULL, "account" text NOT NULL, "event_name" text NOT NULL, "glv_address" text NOT NULL, "market_address" text, "long_token_amount" numeric, "short_token_amount" numeric, "received_glv_tokens" numeric, "key" text NOT NULL, "timestamp" integer NOT NULL, "transaction_id" character varying, CONSTRAINT "PK_bcb5de8c94de821fb5f8a98ea0b" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_6b155fbda0be71722ac5354df6" ON "glv_deposit_action" ("account") `)
        await db.query(`CREATE INDEX "IDX_ee5f3efda689747dca9d9238e1" ON "glv_deposit_action" ("event_name") `)
        await db.query(`CREATE INDEX "IDX_5ccebdbc9ae5c73cefa64c6b4d" ON "glv_deposit_action" ("glv_address") `)
        await db.query(`CREATE INDEX "IDX_90ab2cab7300bdd171d90d61e5" ON "glv_deposit_action" ("key") `)
        await db.query(`CREATE INDEX "IDX_9f43ad7b74abf78be91e42d585" ON "glv_deposit_action" ("timestamp") `)
        await db.query(`CREATE INDEX "IDX_bd08a0fdd61c075137936d2279" ON "glv_deposit_action" ("transaction_id") `)
        await db.query(`CREATE TABLE "glv_withdrawal_action" ("id" character varying NOT NULL, "account" text NOT NULL, "event_name" text NOT NULL, "glv_address" text NOT NULL, "market_address" text, "glv_token_amount" numeric, "received_long_token_amount" numeric, "received_short_token_amount" numeric, "key" text NOT NULL, "timestamp" integer NOT NULL, "transaction_id" character varying, CONSTRAINT "PK_ce4a6c0df1095c24d43b5b3abf0" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_8b5d47d208b16b7df3888fefda" ON "glv_withdrawal_action" ("account") `)
        await db.query(`CREATE INDEX "IDX_e347a3091d13d07f32a7e868cf" ON "glv_withdrawal_action" ("event_name") `)
        await db.query(`CREATE INDEX "IDX_e8b070dd98be8170820c23373e" ON "glv_withdrawal_action" ("glv_address") `)
        await db.query(`CREATE INDEX "IDX_8ecc9100977a5e2fd616fd437b" ON "glv_withdrawal_action" ("key") `)
        await db.query(`CREATE INDEX "IDX_a127446fe54a6bedac79bde260" ON "glv_withdrawal_action" ("timestamp") `)
        await db.query(`CREATE INDEX "IDX_4e1dc52c0a337e9641b66c2058" ON "glv_withdrawal_action" ("transaction_id") `)
        await db.query(`CREATE TABLE "price" ("id" character varying NOT NULL, "token" text NOT NULL, "min_price" numeric NOT NULL, "max_price" numeric NOT NULL, "snapshot_timestamp" integer NOT NULL, "is_snapshot" boolean NOT NULL, "type" text NOT NULL, CONSTRAINT "PK_d163e55e8cce6908b2e0f27cea4" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_0cc67bf87e6c3a16e56327ef3c" ON "price" ("token") `)
        await db.query(`CREATE INDEX "IDX_45e7fbfbd8574a936c00960646" ON "price" ("snapshot_timestamp") `)
        await db.query(`CREATE TABLE "platform_stat" ("id" character varying NOT NULL, "deposited_users" integer NOT NULL, "timestamp" integer NOT NULL, CONSTRAINT "PK_248a3943de0d32ae267a326ede4" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "distribution" ("id" character varying NOT NULL, "receiver" text NOT NULL, "type_id" text NOT NULL, "amounts" text array NOT NULL, "amounts_in_usd" text array NOT NULL, "tokens" text array NOT NULL, "timestamp" integer NOT NULL, "transaction_id" character varying, CONSTRAINT "PK_187eaf203ccf9018df51b40108c" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_5b292ace8bd012742bf215a47a" ON "distribution" ("receiver") `)
        await db.query(`CREATE INDEX "IDX_3f29c2a3df7cabc003ae145fd0" ON "distribution" ("transaction_id") `)
        await db.query(`CREATE INDEX "IDX_280bc2f68470640844bb88eece" ON "distribution" ("timestamp") `)
        await db.query(`ALTER TABLE "trade_action" ADD CONSTRAINT "FK_6a08a35b1cd69e340c608fdfd48" FOREIGN KEY ("transaction_id") REFERENCES "transaction"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "claim_action" ADD CONSTRAINT "FK_4b733c1ff5148f63e68bdb7f8d1" FOREIGN KEY ("transaction_id") REFERENCES "transaction"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "deposit_action" ADD CONSTRAINT "FK_8de64f2caf1adb5ab2b574deadf" FOREIGN KEY ("transaction_id") REFERENCES "transaction"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "withdrawal_action" ADD CONSTRAINT "FK_4aea3902e1d161ae8eab306b989" FOREIGN KEY ("transaction_id") REFERENCES "transaction"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "glv_deposit_action" ADD CONSTRAINT "FK_bd08a0fdd61c075137936d2279b" FOREIGN KEY ("transaction_id") REFERENCES "transaction"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "glv_withdrawal_action" ADD CONSTRAINT "FK_4e1dc52c0a337e9641b66c20585" FOREIGN KEY ("transaction_id") REFERENCES "transaction"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "distribution" ADD CONSTRAINT "FK_3f29c2a3df7cabc003ae145fd02" FOREIGN KEY ("transaction_id") REFERENCES "transaction"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "position" ADD CONSTRAINT "FK_position_account_stat" FOREIGN KEY ("account_stat_id") REFERENCES "account_stat"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    }

    async down(db) {
        await db.query(`DROP TABLE "transaction"`)
        await db.query(`DROP INDEX "public"."IDX_de4f0899c41c688529784bc443"`)
        await db.query(`DROP TABLE "trade_action"`)
        await db.query(`DROP INDEX "public"."IDX_fbe5bb206a653d096b723f9a83"`)
        await db.query(`DROP INDEX "public"."IDX_39d9f66737b783b42b58886d45"`)
        await db.query(`DROP INDEX "public"."IDX_aeddd1ffbafd3791ac95aade2e"`)
        await db.query(`DROP INDEX "public"."IDX_8751bc3ea47c0c373f0942014a"`)
        await db.query(`DROP INDEX "public"."IDX_6a08a35b1cd69e340c608fdfd4"`)
        await db.query(`DROP INDEX "public"."IDX_5413319a6a49c7e4aa3f191b54"`)
        await db.query(`DROP TABLE "position"`)
        await db.query(`DROP INDEX "public"."IDX_a3fa7add1f44aea63006e09e46"`)
        await db.query(`DROP INDEX "public"."IDX_c5575b15c2af612abeedeb69a1"`)
        await db.query(`DROP TABLE "account_stat"`)
        await db.query(`DROP TABLE "period_account_stat"`)
        await db.query(`DROP INDEX "public"."IDX_d48ad46979ace63b6a99c82d2b"`)
        await db.query(`DROP INDEX "public"."IDX_49fb299d0694f14b715a9ea3d5"`)
        await db.query(`DROP TABLE "claim_action"`)
        await db.query(`DROP INDEX "public"."IDX_33744b9169fe21b2074c854119"`)
        await db.query(`DROP INDEX "public"."IDX_30de987ce5da34390955969a16"`)
        await db.query(`DROP INDEX "public"."IDX_4b733c1ff5148f63e68bdb7f8d"`)
        await db.query(`DROP TABLE "claimable_collateral"`)
        await db.query(`DROP INDEX "public"."IDX_96cd78c49099592bff934e39a6"`)
        await db.query(`DROP TABLE "deposit_action"`)
        await db.query(`DROP INDEX "public"."IDX_e4aba1be4c95e97b75423e303e"`)
        await db.query(`DROP INDEX "public"."IDX_10ab0e4970802f405284cf09fd"`)
        await db.query(`DROP INDEX "public"."IDX_485a8a6db05713181d7fb053f7"`)
        await db.query(`DROP INDEX "public"."IDX_745beaf1a91bd7269f32625772"`)
        await db.query(`DROP INDEX "public"."IDX_2c835fdeb834a15d27442b0f62"`)
        await db.query(`DROP INDEX "public"."IDX_8de64f2caf1adb5ab2b574dead"`)
        await db.query(`DROP TABLE "withdrawal_action"`)
        await db.query(`DROP INDEX "public"."IDX_9ee6a688101a9f1433ebb48416"`)
        await db.query(`DROP INDEX "public"."IDX_751ebec57c8dca0dd792498d2f"`)
        await db.query(`DROP INDEX "public"."IDX_226e54d555acc2ff8e497a86d9"`)
        await db.query(`DROP INDEX "public"."IDX_487ae444a372dab62dd88c7fba"`)
        await db.query(`DROP INDEX "public"."IDX_fbaed929abd3390b2f676da218"`)
        await db.query(`DROP INDEX "public"."IDX_4aea3902e1d161ae8eab306b98"`)
        await db.query(`DROP TABLE "market_info"`)
        await db.query(`DROP INDEX "public"."IDX_8f2087423919ebcabfd54d30cf"`)
        await db.query(`DROP TABLE "volume_info"`)
        await db.query(`DROP INDEX "public"."IDX_26a9a2fc81da7ab69d032a6141"`)
        await db.query(`DROP INDEX "public"."IDX_24b9e4d52476c0d729a784988a"`)
        await db.query(`DROP TABLE "positions_volume"`)
        await db.query(`DROP INDEX "public"."IDX_20a3b78659fbd92e1d4e01ec8a"`)
        await db.query(`DROP INDEX "public"."IDX_9f8f59bbb384b9760c0388c4ef"`)
        await db.query(`DROP TABLE "apr_snapshot"`)
        await db.query(`DROP INDEX "public"."IDX_52711af5befe03f9f9f07ef179"`)
        await db.query(`DROP INDEX "public"."IDX_5174013c1a7dd4a570c72d2507"`)
        await db.query(`DROP TABLE "fees_info"`)
        await db.query(`DROP INDEX "public"."IDX_755a9275c12efab4c4a54adef4"`)
        await db.query(`DROP INDEX "public"."IDX_25cadba7648fd93f8232747654"`)
        await db.query(`DROP TABLE "user_stat"`)
        await db.query(`DROP TABLE "glv_deposit_action"`)
        await db.query(`DROP INDEX "public"."IDX_6b155fbda0be71722ac5354df6"`)
        await db.query(`DROP INDEX "public"."IDX_ee5f3efda689747dca9d9238e1"`)
        await db.query(`DROP INDEX "public"."IDX_5ccebdbc9ae5c73cefa64c6b4d"`)
        await db.query(`DROP INDEX "public"."IDX_90ab2cab7300bdd171d90d61e5"`)
        await db.query(`DROP INDEX "public"."IDX_9f43ad7b74abf78be91e42d585"`)
        await db.query(`DROP INDEX "public"."IDX_bd08a0fdd61c075137936d2279"`)
        await db.query(`DROP TABLE "glv_withdrawal_action"`)
        await db.query(`DROP INDEX "public"."IDX_8b5d47d208b16b7df3888fefda"`)
        await db.query(`DROP INDEX "public"."IDX_e347a3091d13d07f32a7e868cf"`)
        await db.query(`DROP INDEX "public"."IDX_e8b070dd98be8170820c23373e"`)
        await db.query(`DROP INDEX "public"."IDX_8ecc9100977a5e2fd616fd437b"`)
        await db.query(`DROP INDEX "public"."IDX_a127446fe54a6bedac79bde260"`)
        await db.query(`DROP INDEX "public"."IDX_4e1dc52c0a337e9641b66c2058"`)
        await db.query(`DROP TABLE "price"`)
        await db.query(`DROP INDEX "public"."IDX_0cc67bf87e6c3a16e56327ef3c"`)
        await db.query(`DROP INDEX "public"."IDX_45e7fbfbd8574a936c00960646"`)
        await db.query(`DROP TABLE "platform_stat"`)
        await db.query(`DROP TABLE "distribution"`)
        await db.query(`DROP INDEX "public"."IDX_5b292ace8bd012742bf215a47a"`)
        await db.query(`DROP INDEX "public"."IDX_3f29c2a3df7cabc003ae145fd0"`)
        await db.query(`DROP INDEX "public"."IDX_280bc2f68470640844bb88eece"`)
        await db.query(`ALTER TABLE "trade_action" DROP CONSTRAINT "FK_6a08a35b1cd69e340c608fdfd48"`)
        await db.query(`ALTER TABLE "claim_action" DROP CONSTRAINT "FK_4b733c1ff5148f63e68bdb7f8d1"`)
        await db.query(`ALTER TABLE "deposit_action" DROP CONSTRAINT "FK_8de64f2caf1adb5ab2b574deadf"`)
        await db.query(`ALTER TABLE "withdrawal_action" DROP CONSTRAINT "FK_4aea3902e1d161ae8eab306b989"`)
        await db.query(`ALTER TABLE "glv_deposit_action" DROP CONSTRAINT "FK_bd08a0fdd61c075137936d2279b"`)
        await db.query(`ALTER TABLE "glv_withdrawal_action" DROP CONSTRAINT "FK_4e1dc52c0a337e9641b66c20585"`)
        await db.query(`ALTER TABLE "distribution" DROP CONSTRAINT "FK_3f29c2a3df7cabc003ae145fd02"`)
        await db.query(`ALTER TABLE "position" DROP CONSTRAINT "FK_position_account_stat"`)
        await db.query(`DROP INDEX "public"."IDX_position_account_stat"`)
    }
}
